/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Pin = IDL.Record({
  'latitude' : IDL.Float64,
  'memo' : IDL.Text,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createPin' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Text], [IDL.Nat], []),
  'getAllPins' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Pin))], ['query']),
  'getPin' : IDL.Func([IDL.Nat], [Pin], ['query']),
  'getPinsByLocationRange' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Pin))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Pin = IDL.Record({
    'latitude' : IDL.Float64,
    'memo' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    'createPin' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Text], [IDL.Nat], []),
    'getAllPins' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Pin))], ['query']),
    'getPin' : IDL.Func([IDL.Nat], [Pin], ['query']),
    'getPinsByLocationRange' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Pin))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };